apiVersion: v1
kind: Service
metadata:
  name: jenkinksservice
  namespace: jenkins
spec:
  selector:
    app: jenkinsapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer